### ISSUE TITLE
Example puppet

### ISSUE THREAD

**Issue by you-win** [Inochi2D/inochi2d#7]
I'm working on a `.vrm` face tracking [app](https://github.com/you-win/openseeface-gd) and was planning on adding Live2D support. I was informed that this project would be a good open-source alternative.

I poked through a few of the associated repos but didn't see an example puppet anywhere. Is there a reference puppet available?

**Comment by ItsRogueRen** [comment]
This is still being worked on, Luna mentioned a working version has a rough ETA of end of next month

**Comment by LunaTheFoxgirl** [comment]
There is plans to provide at least an example puppet w/ [Inochi Creator](https://github.com/Inochi2D/inochi-creator) at some point. Will be once I feel Inochi2D and Inochi Creator are in more generally usable states

**Comment by LunaTheFoxgirl** [comment]
I will add that the INP file format that Inochi2D uses is documented on the wiki in these places
https://github.com/Inochi2D/inochi2d/wiki/INP-Data-Interchange-Format
https://github.com/Inochi2D/inochi2d/wiki/JSON-Data-Specification

**Comment by you-win** [comment]
Thanks for that! I'll keep those pages in mind when I start development myself

**Comment by LunaTheFoxgirl** [comment]
Small update: A mascot character is being designed for Inochi2D which I plan to eventually ship with Inochi Creator. So work is undergoing on this issue.

**Comment by LunaTheFoxgirl** [comment]
Another update, this is the project's new mascot! 
Designed by [Kinugitsune](https://twitter.com/kinugitsune).  

![image](https://user-images.githubusercontent.com/7032834/144473626-d74fe3b9-8e26-4441-a233-207e5c282614.png)

Am already in a waiting list to commission a model of her from an other artist, with a sponsor paying the model, should be my turn around the end of December :)

**Comment by LunaTheFoxgirl** [comment]
Another update, the model is in the process of being made now. The artist for the actual model that will be featured in app is [ku-ini](https://twitter.com/duckmastah)! :)

Here's the sketch I've gotten from her so far, more to come. And she has streamed work on it today (23rd of February) https://www.twitch.tv/videos/1307587283
![image](https://user-images.githubusercontent.com/7032834/155421169-33c28c50-ddd6-4efb-b858-859979a3a586.png)

**Comment by LunaTheFoxgirl** [comment]
Update on this, example models made by seagetch will be featured in the next update. Which I hope to release sometime this month.

A partial version of the Ada model will also be available once I'm done rigging her, as well. But probably will be for a later version ^^;

**Comment by grandpaul** [comment]
Hi Luna,

Sorry for bothering. I'd like to know if I have some misunderstanding on these models and the project.

I'm from Debian and am a Debian developer. Sometimes I'll be a vTuber if I don't want to show up my face. 
I have some interest to integrate Inochi2D into Debian by packaging it directly in Debian. And start using Inochi2D as my vTuber engine rather than crafting it by hand. 

However when I look into the whole project, I noticed that Inochi2D/branding has a different license. 
And it seems to me that it is not compliance with DFSG. I mean the license doesn't look like those majority open source licenses. Does that mean I can only package Inochi2D without any Inochi2D branding materials?

And I'm not sure if I'm correct, but the logo (trademark) also needs to be avoided, right? 
Does that mean if I want to package Inochi2D in Debian (which is not officially release by you), should I rename Inochi2D to something else? 
In Debian, we did rename Firefox to IceWeasel before because Debian didn't get the permission to use Firefox's trademark. Which I think that is not good. But now this problem is solved because Firefox allows us to use that name. I'd like to know if I need to do the same thing when packaging Inochi2D.

Many Thanks,
Paul Liu

**Comment by LunaTheFoxgirl** [comment]
You only need to omit branding resources, which is the default compilation mode, just stick to the compilation modes called "barebones" and you'll be fine. Do note that non-official packages not by the Inochi2D project will have a large "(UNSUPPORTED)" part in the titlebar, and bugs that happen to appear in unsupported builds needs to be replicateable in the official builds to ensure it's not a packaging/library version problem. The logo counts as branding and is omitted for these builds automatically, at some point I'll probably provide a fallback logo for unofficial builds.

The Inochi2D library itself has no branding resources, but you wouldn't want to package the library itself as it's meant to be statically compiled in to your app, as per how D functions.

The only model that is also counted as branding resources is the project's mascot, so these new models in the works should be able to be included with versions compiled for unofficial packages.



The main reason we're doing this is:
1. To make sure that we can provide an even experience for Inochi2D across platforms where you can expect it to just work the same
2. To make it clear to our users when a build isn't official, and thus we don't officially test for issues on there.
3. To allows us to control who and which projects we want to associate with more directly.

**Comment by LunaTheFoxgirl** [comment]
@you-win there's now the Aka and Midori example models available in this repository. Closing the issue.
https://github.com/Inochi2D/example-models
